### ISSUE TITLE
pip3 install not working for cairosvg

### ISSUE THREAD

**Issue by kesdogan** [ellerbrock/osx-python-pip-problems#1]
Hi all,

I have been trying to install cairosvg using the "pip3 install cairosvg" command.

I always get the error term

"python setup.py egg_info" failed with error code 1 in

and then depending on whether I had run it with sudo powers or not, I get listed the folders

/private/tmp/pip-build-19ynye6w/cairocffi/ (for sudo)

or

/private/var/folders/z8/0m4tj0x14yb75l37vybt1zx00000gp/T/pip-build-zc8buluu/cairocffi/ (for non sudo)

I have tried everything from updating the pip3 setuptools to installing brew and trying to install cairosvg that way.
What would you recommend?

**Comment by ellerbrock** [comment]
hi @tlk13,

i'm not really a python guy,
you could try to just run [cairosvg docker container](https://hub.docker.com/r/pypi/cairosvg/) and not further care about it :)

cheers maik

**Comment by kesdogan** [comment]
Thanks @ellerbrock for your help. I actually found a solution by this page [https://github.com/Kozea/CairoSVG/issues/183](url)

If any one has the problem, just check that out, worked perfect for me.
